export interface MenuItem {
  id: string
  name: string
  description: string
  price: number
  cost_price?: number
  category: string
  image_url: string | null
  is_available: boolean
  rating_avg?: number
  rating_count?: number
}

export const defaultCategories = [
  'Semua',
  'Makanan Berat',
  'Snack',
  'Milky Series',
  'Renceng Series',
  'Lokal Series',
  'Tea Series',
  'Coffee Series',
  'Mocktail Series',
]

export const categoryColors: Record<string, string> = {
  'Makanan Berat': '#e85a4a',
  Snack: '#c47a2e',
  'Milky Series': '#a04ae8',
  'Renceng Series': '#2e7ac4',
  'Lokal Series': '#4a9e6a',
  'Tea Series': '#2ec4a0',
  'Coffee Series': '#7a4a2e',
  'Mocktail Series': '#e84a90',
}

export const defaultMenuItems: MenuItem[] = [
  // --- Makanan Berat ---
  {
    id: 'mb-1',
    name: 'Seblak Prasmanan',
    description: 'Seblak kuah pedas gurih dengan aneka pilihan topping prasmanan segar.',
    price: 12000,
    category: 'Makanan Berat',
    image_url: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'mb-2',
    name: 'Mie Nyemek / Goreng',
    description: 'Olahan mie bumbu racikan gurih mantap dengan sayur dan telur.',
    price: 8000,
    category: 'Makanan Berat',
    image_url: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'mb-3',
    name: 'Ayam Geprek',
    description: 'Ayam krispi renyah digeprek dengan sambal bawang pedas nampol.',
    price: 12000,
    category: 'Makanan Berat',
    image_url: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },

  // --- Snack ---
  {
    id: 'sn-1',
    name: 'Pisang Pasir (M)',
    description: 'Pisang manis balut tepung panir krispi renyah porsi Medium.',
    price: 6000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-2',
    name: 'Pisang Pasir (L)',
    description: 'Pisang pasir krispi porsi Large melimpah pas untuk dinikmati bersama.',
    price: 10000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-3',
    name: 'Piscok (M)',
    description: 'Pisang coklat lumer dibalut kulit lumpia renyah porsi Medium.',
    price: 6000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1607920591413-4ec007e70023?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-4',
    name: 'Piscok (L)',
    description: 'Pisang coklat lumer ekstra coklat meleleh porsi Large.',
    price: 10000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1607920591413-4ec007e70023?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-5',
    name: 'Dimsum',
    description: 'Dimsum kukus lembut isi olahan daging ayam dan udang gurih lezat.',
    price: 10000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-6',
    name: 'Tahu Kres',
    description: 'Tahu goreng berbalut tepung krispi gurih renyah.',
    price: 5000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-7',
    name: 'Cireng Isi (M)',
    description: 'Cireng kenyal isi ayam pedas gurih porsi Medium.',
    price: 6000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-8',
    name: 'Cireng Isi (L)',
    description: 'Cireng kenyal isi ayam pedas gurih porsi Large puas.',
    price: 10000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-9',
    name: 'Cilok Aci',
    description: 'Cilok kenyal gurih disajikan dengan bumbu kacang atau saus pedas.',
    price: 5000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-10',
    name: 'Tahu Kocek (M)',
    description: 'Tahu kocek khas dengan sambal cabe uleg rawit segar porsi Medium.',
    price: 6000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-11',
    name: 'Tahu Kocek (L)',
    description: 'Tahu kocek khas sambal cabe rawit pedas mantap porsi Large.',
    price: 10000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-12',
    name: 'Kocek Mix (M)',
    description: 'Kombinasi tahu dan cilok bumbu kocek pedas porsi Medium.',
    price: 6000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-13',
    name: 'Kocek Mix (L)',
    description: 'Kombinasi tahu dan cilok bumbu kocek pedas porsi Large.',
    price: 10000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-14',
    name: 'Kentang Goreng',
    description: 'Kentang goreng stik renyah gurih disajikan dengan saus cocol.',
    price: 6000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-15',
    name: 'Mix Platter',
    description: 'Platter camilan lengkap kentang, sosis, dan nugget dalam satu piring.',
    price: 10000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-16',
    name: 'Basreng (M)',
    description: 'Bakso goreng krispi renyah bumbu pedas daun jeruk porsi Medium.',
    price: 6000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-17',
    name: 'Basreng (L)',
    description: 'Bakso goreng krispi renyah bumbu pedas daun jeruk porsi Large.',
    price: 10000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-18',
    name: 'Sosis Bakar',
    description: 'Sosis panggang gurih diolesi saus barbeque lezat manis pedas.',
    price: 5000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-19',
    name: 'Bakaran Seafood',
    description: 'Aneka sate olahan seafood bakar saus istimewa per porsi.',
    price: 10000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-20',
    name: 'Risoles',
    description: 'Risoles isi creamy lezat dengan kulit renyah keemasan per porsi.',
    price: 10000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-21',
    name: 'Burger Beef',
    description: 'Burger daging sapi gurih dengan sayuran segar dan saus spesial.',
    price: 8000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-22',
    name: 'Pentol Mercon',
    description: 'Pentol daging sapi kenyal dimasak dalam sambal cabe rawit mercon membakar lidah.',
    price: 10000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-23',
    name: 'Donat Toping (M)',
    description: 'Donat lembut aneka topping coklat/keju porsi Medium.',
    price: 6000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-24',
    name: 'Donat Toping (L)',
    description: 'Donat lembut aneka topping porsi Large istimewa.',
    price: 10000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-25',
    name: 'Getuk Goreng',
    description: 'Getuk singkong manis legit digoreng renyah di luar lembut di dalam.',
    price: 6000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-26',
    name: 'Corndog Mozza',
    description: 'Corndog krispi lumer keju mozzarella mulur dengan saus mayonaise dan sambal.',
    price: 8000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1628294895950-9805252327bc?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'sn-27',
    name: 'Corndog Sosis',
    description: 'Corndog renyah isi sosis daging gurih nikmat.',
    price: 7000,
    category: 'Snack',
    image_url: 'https://images.unsplash.com/photo-1628294895950-9805252327bc?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },

  // --- Milky Series ---
  {
    id: 'mk-1',
    name: 'Ice Milky Matcha',
    description: 'Perpaduan susu segar creamy dan bubuk matcha aromatik dingin segar.',
    price: 8000,
    category: 'Milky Series',
    image_url: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'mk-2',
    name: 'Ice Milky Choco',
    description: 'Susu segar berpadu coklat pekat lezat pelepas dahaga.',
    price: 8000,
    category: 'Milky Series',
    image_url: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'mk-3',
    name: 'Ice Milky Taro',
    description: 'Rasa taro manis lembut dengan susu creamy segar berwarna ungu memikat.',
    price: 8000,
    category: 'Milky Series',
    image_url: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'mk-4',
    name: 'Ice Milky Redvelvet',
    description: 'Red velvet manis gurih berpadu susu dingin segar.',
    price: 8000,
    category: 'Milky Series',
    image_url: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },

  // --- Renceng Series ---
  {
    id: 'rc-1',
    name: 'Pop Ice',
    description: 'Minuman blender dingin segar aneka rasa nostalgia.',
    price: 4000,
    category: 'Renceng Series',
    image_url: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'rc-2',
    name: 'Nutrisari',
    description: 'Minuman sari jeruk kaya vitamin C disajikan dingin menyegarkan.',
    price: 4000,
    category: 'Renceng Series',
    image_url: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },

  // --- Lokal Series ---
  {
    id: 'lk-1',
    name: 'Ice Jeruk',
    description: 'Jeruk peras alami segar disajikan dingin dengan es batu.',
    price: 4000,
    category: 'Lokal Series',
    image_url: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'lk-2',
    name: 'Hot Jeruk',
    description: 'Jeruk peras hangat alami melegakan tenggorokan.',
    price: 4000,
    category: 'Lokal Series',
    image_url: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'lk-3',
    name: 'Hot Tea',
    description: 'Teh seduh hangat wangi melati alami dengan gula asli.',
    price: 4000,
    category: 'Lokal Series',
    image_url: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'lk-4',
    name: 'Es Teh Jumbo',
    description: 'Es teh manis segar disajikan dalam gelas porsi jumbo puas.',
    price: 4000,
    category: 'Lokal Series',
    image_url: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'lk-5',
    name: 'Es Teler (Musiman)',
    description: 'Es teler santan segar isi alpukat, kelapa muda, dan nangka (ketersediaan musiman).',
    price: 10000,
    category: 'Lokal Series',
    image_url: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'lk-6',
    name: 'Es Jagung (Musiman)',
    description: 'Es jagung manis creamy khas dengan susu dan parutan keju (ketersediaan musiman).',
    price: 10000,
    category: 'Lokal Series',
    image_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },

  // --- Tea Series ---
  {
    id: 'te-1',
    name: 'Ice Lychee Tea',
    description: 'Teh aromatik dipadukan sirup leci manis segar dengan buah leci dingin.',
    price: 6000,
    category: 'Tea Series',
    image_url: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'te-2',
    name: 'Ice Lemon Tea',
    description: 'Teh segar dengan perasan lemon asli dingin pelepas dahaga.',
    price: 6000,
    category: 'Tea Series',
    image_url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },

  // --- Coffee Series ---
  {
    id: 'cf-1',
    name: 'Black Coffee',
    description: 'Kopi hitam seduh aromatik khas biji kopi pilihan.',
    price: 5000,
    category: 'Coffee Series',
    image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'cf-2',
    name: 'Nescafe Latte Ice',
    description: 'Kopi latte creamy Nescafe disajikan dingin menyegarkan.',
    price: 9000,
    category: 'Coffee Series',
    image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'cf-3',
    name: 'Nescafe Latte Hot',
    description: 'Kopi latte hangat lembut menenangkan dari Nescafe.',
    price: 7000,
    category: 'Coffee Series',
    image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'cf-4',
    name: 'Americano (Ice/Hot)',
    description: 'Espresso dengan air mineral segar (pilihan Ice / Hot, gula / no sugar).',
    price: 5000,
    category: 'Coffee Series',
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'cf-5',
    name: 'Brown Sugar Coffee Latte',
    description: 'Kopi susu lembut berpadu lelehan gula aren murni aromatik.',
    price: 9000,
    category: 'Coffee Series',
    image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'cf-6',
    name: 'Butterscotch Coffee Latte',
    description: 'Kopi susu berpadu aroma sirup butterscotch manis gurih karamel.',
    price: 9000,
    category: 'Coffee Series',
    image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },

  // --- Mocktail Series ---
  {
    id: 'mc-1',
    name: 'Blood Sparkling',
    description: 'Mocktail merah segar bersoda dengan kombinasi sirup berry manis menggigit.',
    price: 8000,
    category: 'Mocktail Series',
    image_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'mc-2',
    name: 'Melon Squash',
    description: 'Kesegaran sirup melon berpadu soda dingin dan bulir selasih.',
    price: 8000,
    category: 'Mocktail Series',
    image_url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
  {
    id: 'mc-3',
    name: 'Lemon Squash',
    description: 'Kesegaran perasan lemon asli bersoda dingin nendang pelepas dahaga.',
    price: 8000,
    category: 'Mocktail Series',
    image_url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    is_available: true,
  },
]
